[package]
name = "rusty-ray-tracer"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "random_scene"
# path = "src/random_scene.rs"

[dependencies]
glam = "0.24.0"
image = "0.24.6"
indicatif = "0.17.3"
rand = "0.8.5"
rayon = "1.7.0"
